version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: No-op
          command: echo "This job doesn't do anything meaningful."

workflows:
  version: 2
  build_workflow:
    jobs:
      - build
